### ISSUE TITLE
Discuss upgrading junit version

### ISSUE THREAD

**Issue by ztkmkoo** [ztkmkoo/dss#61]
Please discuss about upgrading junit version 4 to 5, and if need please commit codes.
After upgrade, make sure all the origin tests run.

**Comment by ztkmkoo** [comment]
I think, it is better to upgrade to junit5.
First it is better to asynchrous test, and some new functions.

But, i never try it, maybe some issues there. I need help

**Comment by yeonnseok** [comment]
I think using junit5 is good option.
I will try to change version.

Also I want to discuss about two more another issues about test code.
1. I want to suggest adding `@DisplayName` above each test method to recognize easily what test is about.
2. There is another library called "AssertJ" which is recommended to use with junit5 because of its fluency of writing test assertions. Especially in collections, exceptions, objects..
[Introduction to AssertJ](https://www.baeldung.com/introduction-to-assertj)
Do you think it is worth applying AssertJ library in our project?

I also want to hear anyone's good other opinions about test code. 
thanks.

**Comment by ztkmkoo** [comment]
> I think using junit5 is good option.
> I will try to change version.
> 
> Also I want to discuss about two more another issues about test code.
> 
> 1. I want to suggest adding `@DisplayName` above each test method to recognize easily what test is about.
> 2. There is another library called "AssertJ" which is recommended to use with junit5 because of its fluency of writing test assertions. Especially in collections, exceptions, objects..
>    [Introduction to AssertJ](https://www.baeldung.com/introduction-to-assertj)
>    Do you think it is worth applying AssertJ library in our project?
> 
> I also want to hear anyone's good other opinions about test code.
> thanks.

Sorry.. I missed your comment. And i have some question for it.
1. @DisplayName shows the name of the test or description of the test? What is the different from change the method name or class name?
2. I agree with your idea that use AssertJ! That's greate!
